Update build-release.yml

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -12,8 +12,13 @@ jobs:
         with:
           swap-storage: false
 
-      - name: Download OpenWrt Image Builder
-        run: wget -qO- https://downloads.openwrt.org/releases/24.10.0/targets/ipq40xx/generic/openwrt-imagebuilder-24.10.0-ipq40xx-generic.Linux-x86_64.tar.zst | tar --zstd -xf -
+      - name: Download OpenWrt SNAPSHOT Image Builder
+        run: wget -qO- https://downloads.openwrt.org/snapshots/targets/ipq40xx/generic/openwrt-imagebuilder-ipq40xx-generic.Linux-x86_64.tar.zst | tar --zstd -xf -
+
+      - name: Check Available Profiles
+        run: |
+          cd openwrt-imagebuilder-*
+          make info | grep -i "mercury\|kt-708\|ti04" || echo "PROFILE NOT FOUND IN SNAPSHOT EITHER"
 
       - name: Inject Passwall2 Repositories
         run: |
